services:
  - type: web
    name: comparador-pbi
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
